### ISSUE TITLE
BufferLayout error when using createTransfer module to create a transaction

### ISSUE THREAD

**Issue by tyirenkyi** [solana-labs/solana-pay#106]
I ran into this bug when writing tests for the link-request branch. You can check out my code [here](https://github.com/tyirenkyi/solana-pay/tree/sdk-tests). Please check out the **_sdk-tests_** branch

**Error**
TypeError: b must be a Uint8Array

      127 |
      128 |     // Create an instruction to transfer native SOL
    > 129 |     return SystemProgram.transfer({
          |                          ^
      130 |         fromPubkey: sender,
      131 |         toPubkey: recipient,
      132 |         lamports,

      at checkUint8Array (node_modules/@solana/web3.js/node_modules/@solana/buffer-layout/src/Layout.ts:149:11)
      at uint8ArrayToBuffer (node_modules/@solana/web3.js/node_modules/@solana/buffer-layout/src/Layout.ts:157:3)
      at UInt.Object.<anonymous>.UInt.encode (node_modules/@solana/web3.js/node_modules/@solana/buffer-layout/src/Layout.ts:610:5)
      at Structure.encode (node_modules/@solana/web3.js/node_modules/@solana/buffer-layout/src/Layout.ts:1311:26)
      at encodeData (node_modules/@solana/web3.js/src/instruction.ts:25:15)
      at Function.transfer (node_modules/@solana/web3.js/src/system-program.ts:695:14)
      at createSystemInstruction (src/createTransfer.ts:129:26)
      at createTransfer (src/createTransfer.ts:64:11)
      at Object.<anonymous> (test/createTransfer.test.ts:62:25)

  ● createTransfer › should return an spl transaction

    TypeError: b must be a Uint8Array

      168 |
      169 |     // Create an instruction to transfer SPL tokens, asserting the mint and decimals match
    > 170 |     return createTransferCheckedInstruction(senderATA, splToken, recipientATA, sender, tokens, mint.decimals);
          |                                            ^
      171 | }
      172 |

      at checkUint8Array (node_modules/@solana/buffer-layout/src/Layout.ts:149:11)
      at uint8ArrayToBuffer (node_modules/@solana/buffer-layout/src/Layout.ts:157:3)
      at UInt.encode (node_modules/@solana/buffer-layout/src/Layout.ts:588:5)
      at Structure.encode (node_modules/@solana/buffer-layout/src/Layout.ts:1205:26)
      at createTransferCheckedInstruction (node_modules/@solana/spl-token/src/instructions/transferChecked.ts:63:36)
      at createSPLTokenInstruction (src/createTransfer.ts:170:44)
      at createTransfer (src/createTransfer.ts:63:11)
      at Object.<anonymous> (test/createTransfer.test.ts:74:25)

**Comment by jordansexton** [comment]
Hmm I can't really tell what's going on, but this sounds like an issue with the new test rather than the `createTransfer` function itself. I would suggest opening a PR from your branch to the `link-request` branch and we can comment on that PR instead of an issue since this doesn't affect the `master` branch.

Looking at your code, I'm guessing the issue is related to this line? https://github.com/tyirenkyi/solana-pay/blob/7a935665ee5c91fd8e6aca5582eb10a300d4ba21/core/test/createTransfer.test.ts#L11

**Comment by C-o-d-e-C-o-w-b-o-y** [comment]
For others encountering this issue, it seems to be `jest`-specific. 

I was able to add the following to `jest.config.js` (or your respective config file) to fix:

```
export default {
	globals: {
		Uint8Array: Uint8Array,
	},
};
```
